@startuml
start

repeat
  :1. описание задачи;
  :2. формализация в алгоритм;
  :3. тесты;
  :4. реализация+комментирование;
  :5. тестовый deploy;
  :6. анализ\nпроверка соответствия;
repeat while (требуется доработка?) is (да)
->нет;
:7. завершение\nпереход к другой задаче;

stop

@enduml