site_name: Система 'ГРАФ'
theme: 'mkdocs'
#theme: 'readthedocs'
plugins:
  - mkpdfs
markdown_extensions:
  - codehilite
  - markdown.extensions.admonition
use_directory_urls: false
site_description: Открытая документация для ГРАФ - Графического Редактора Алгоритмов и Функций
copyright: В.Куликов, для НПП "ЭиС", 2020
pages:
  - 'Главная': 'index.md'
  - 'Руководство разработчика':
      - '1. Правила': 'code_manual/rules.md'
      - '2. Спецификация': 'code_manual/specs.md'
      - '3. История разработки': 'code_manual/dev_history.md'
  - 'Руководство пользователя':
      - '1. Кухня': 'user_manual/user_manual_start.md'
